runtime: nodejs10
service: script

env_variables:
  DB_USER: "root"
  DB_NAME: "script"
  DB_PASS: "communicare100%safe"
  DB_INSTANCE_UNIX_SOCKET: "/cloudsql/communicare-staging:asia-southeast2:communicare-db"