version: '3.3'
services:
  db:
    image: mysql/mysql-server:8.0.32
    restart: always
    environment:
      # - MYSQL_DATABASE=appsDB
      # # So you don't have to use root, but you can if you like
      # - MYSQL_USER=user
      # # You can use whatever password you like
      # - MYSQL_PASSWORD=db_password
      # Password for root access
      - MYSQL_ROOT_PASSWORD='$ecure_R00T_password'
      - MYSQL_ROOT_HOST='%''
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8080:8080'
    expose:
      # 8080 port 3306 on the container
      - '8080'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  db-admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Names our volume
volumes:
  my-db:
